### ISSUE TITLE
盾构隧道限界过窄导致信号设备不能正常布置

### ISSUE THREAD

**Issue by winup-zhou** [noname390/BVE-Gensokyo-Railway#18]
地下段的盾构隧道宽度感觉有点过窄...只能满足一般信号机的布置，无法满足进路表示器的布置需求
![baaa18923c588c44da47b6cc04e0fea2](https://github.com/noname390/BVE-Gensokyo-Railway/assets/60384089/39297bb0-c230-4904-a844-9308c4233aa2)

**Comment by noname390** [comment]
这个问题有点难解决，好像只有换一种进路表示器的样式或者重新建一个隧道的模型才行
(这个隧道的模型是素材包自带的)
